import numpy as np
from hmm import HMM
from forward_backward import forward_algorithm, backward_algorithm, compute_gamma_xi
from viterbi import viterbi_algorithm
from data_loader import load_data

np.set_printoptions(threshold=np.inf)


# 讀取數據
observations = load_data("train_data.txt")

# 檢查數據是否為空
if len(observations) == 0:
    print("Error: Observations sequence is empty! Check your train_data.txt file.")
    exit()

print("\nObservation Sequence Loaded:", len(observations), "observations.")

# 初始化 HMM
num_states = 2  # High / Low
num_observations = 4  # DNA 碱基（A, C, G, T）
hmm = HMM(num_states, num_observations)

# Baum-Welch 訓練
max_iterations = 100  # 訓練最大迭代次數
min_iterations = 10   # 最少訓練次數，避免過早收斂
tolerance = 1e-6      # 收斂條件
epsilon = 1e-10       # 避免數值問題
previous_A = np.copy(hmm.A)  # 儲存上一輪的 A
previous_B = np.copy(hmm.B)  # 儲存上一輪的 B

print("\nStarting Baum-Welch training...")

for iteration in range(max_iterations):
    alpha = forward_algorithm(hmm, observations)
    beta = backward_algorithm(hmm, observations)
    gamma, xi = compute_gamma_xi(hmm, observations, alpha, beta)

    # 檢查 gamma 和 xi 是否為 NaN
    if np.isnan(gamma).any() or np.isnan(xi).any():
        print(f"Error: NaN detected in gamma or xi during iteration {iteration}, skipping update.")
        continue

    # 更新 HMM 參數
    hmm.update_parameters(gamma, xi, observations)

    # 計算參數變化量（總變動量）
    delta_A = np.sum(np.abs(hmm.A - previous_A))
    delta_B = np.sum(np.abs(hmm.B - previous_B))

    print(f"Iteration {iteration}: ΔA = {delta_A:.6f}, ΔB = {delta_B:.6f}")

    # 收斂條件
    if iteration >= min_iterations and delta_A < tolerance and delta_B < tolerance:
        print("Converged! Stopping training early.")
        break

    previous_A = np.copy(hmm.A)
    previous_B = np.copy(hmm.B)

# 印出最終的 HMM 參數
print("\nFinal HMM Parameters:")
print("Initial Probabilities (π):")
print(hmm.pi)
print("\nTransition Matrix (A):")
print(hmm.A)
print("\nEmission Matrix (B):")
print(hmm.B)

# 使用 Viterbi 推斷隱狀態
hidden_states = viterbi_algorithm(hmm, observations)

if len(hidden_states) == 0:
    print("Error: Viterbi algorithm returned an empty sequence!")
else:
    print("\nMost Likely Hidden States:")
    print(hidden_states)

# 將參數寫入 model.py
with open("model.py", "w") as f:
    f.write("# HMM Model Parameters (Generated by training)\n")
    f.write("import numpy as np\n\n")
    f.write(f"A = np.array({repr(hmm.A.tolist())})\n")
    f.write(f"B = np.array({repr(hmm.B.tolist())})\n")
    f.write(f"pi = np.array({repr(hmm.pi.tolist())})\n")
